site_name: Coach Candor User Guides
site_description: 'Customer user guides for Coach Candor'
site_author: 'Coach Candor Team'
docs_dir: docs/
repo_name: 'user-guides'
repo_url: 'https://github.com/coachcandor/user-guides/'
theme:
  name: 'material'
  features:
    - navigation.instant
nav:
    - Home: index.md
